<a href="https://colab.research.google.com/github/joje3029/AI_Study/blob/main/7%EC%8B%9C_%EC%88%98%EC%97%85_2023_07_13_%ED%8C%90%EB%8B%A4%EC%8A%A4_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd

In [48]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [49]:
coler = pd.Series(["white","Red","blue"], name = "coler")


coler[2]

'blue'

In [50]:
## 데이터 프레임 만들기

data = {
        "이름" : ["홍길동", "이순신", "임꺽정"],
        "나이" : [22, 33, 29],
        "학교" : ["서울대","고려대","연세대"]
    }

student=pd.DataFrame(data)

In [51]:
## 데이터 접근
# 기본적으로 시리즈 단위로 접근

student

    이름  나이   학교
0  홍길동  22  서울대
1  이순신  33  고려대
2  임꺽정  29  연세대

In [52]:
# 데이터 프레임에서 열과 행을 동시에 선택하는 방법
student.loc[[0,2],['이름','학교']]

    이름   학교
0  홍길동  서울대
2  임꺽정  연세대

In [53]:
# 파일로 저장하기
student.to_csv('student.csv', index=False)
# 저장할 때 index=False 안하면 인덱스번호도 통채로 저장됨. 불러오기 했을때 인덱스도 같이 나옴.
# 꼴 이상하게 됨.

In [54]:
# csv 저장한 파일을 불러오기
df=pd.read_csv('student.csv')

df

    이름  나이   학교
0  홍길동  22  서울대
1  이순신  33  고려대
2  임꺽정  29  연세대

In [55]:
df=pd.read_excel('/content/Github/거래내역조회.xlsx', skiprows=3)

df

,No.,거래일시,적요,기재내용,찾으신금액,맡기신금액,거래후 잔액,취급점,메모
0,1,2022.03.12 03:37,ＣＭＳ,NaN,9570,0,26213,유성금융센터,NaN
1,2,2022.03.11 03:26,통신요금,01011112222SKT,117910,0,35783,유성금융센터,NaN
2,3,2022.03.10 18:23,체크우리,김밥이 좋아,4500,0,153693,영업추진부(카드),NaN
3,4,2022.03.10 16:05,체크우리,스타벅스,2000,0,158193,영업추진부(카드),NaN
4,5,2022.03.10 10:42,체크우리,몸짱피트니스,238000,0,160193,영업추진부(카드),NaN
5,6,2022.03.10 10:40,타행이체,친구,0,100000,398193,KB증권,NaN
6,7,2022.03.10 00:59,펌뱅킹,이커머스,15540,0,198193,유성금융센터,NaN
7,8,2022.03.09 18:49,체크우리,커피집,2000,0,213733,영업추진부(카드),NaN
8,9,2022.03.09 18:05,타행이체,가족,0,200000,215733,KB증권,NaN
9,10,2022.03.09 16:52,체크우리,피자집,9800,0,15733,영업추진부(카드),NaN

In [56]:
# loc, iloc 이용한 데이터 접근 방법
# loc 단일 선택 -> row 기준
df.loc[0]
# 다중 선택
df.loc[[0,2,5]]
# 슬라이싱 : 어디서 어디까지 잘라서 가져와라
df.loc[0:5]
df2=df.loc[0:5:2]
# 논리 인덱싱 : 중요. True/False 말함. 논리값 갯수는 row 개수랑 일치해야함. flase로 쓰면 해당 row 출력 안함.
df2.loc[[True, True, True]]

# row와 column을 같이 선택 : 단일인지 다중인지 슬라이싱인지 논리인지는 응용하기에 따라 다 사용가능
df.loc[0,'찾으신금액']
df.loc[0:5,['찾으신금액','맡기신금액',	'거래후 잔액'	]]

# 특정 조건을 만족하는 행만 선택하고 싶을 때
# 예) 찾으신 금액이 10만원 이상인 행만 선택.

# 판다스에서는 for문과 if 문으로 따로 안해도 아래와 같이 하면 자동으로 논리 인덱싱을 해줌.
df['찾으신금액']>100000
# 아래와 같이 하면 True인 row의 내용이 출력
df.loc[df['찾으신금액']>100000]
# 이거 문법 잘 알아두기! 문법때매 헤메것네
df.loc[(df['찾으신금액']>100000) & (df['적요']=='통신요금')]

,No.,거래일시,적요,기재내용,찾으신금액,맡기신금액,거래후 잔액,취급점,메모
1,2,2022.03.11 03:26,통신요금,01011112222SKT,117910,0,35783,유성금융센터,NaN

In [57]:
stu = pd.read_excel('/content/Github/students.xlsx')

stu

     번호   이름  국어  영어  수학 지역명       생년월일
0     1  이현진  68  77  81  대전 2050-08-17
1     2  장민동  84  97  88  광주 2050-08-02
2     3  강준은  63  85  64  울산 2050-10-22
3     4  강혜희  99  95  79  서울 2050-05-27
4     5  김혜수  83  76  67  대전 2050-01-25
..  ...  ...  ..  ..  ..  ..        ...
95   96  이민운  99  63  65  서울 2050-08-18
96   97  장혜운  90  86  62  대전 2050-10-08
97   98  박철동  90  96  60  대전 2050-03-01
98   99  강준동  62  69  69  광주 2050-11-24
99  100  이현운  84  91  73  서울 2050-07-20

[100 rows x 7 columns]

In [58]:
import pandas as pd
from tables import index
# 1. students파일을 읽어서 데이터 프레임으로 만든 후 아래를 해결해주세요.
stu = pd.read_excel('/content/Github/students.xlsx')
# 2. 국어가 80점 이상인 학생의 이름과 생년월일
stu.loc[stu['국어']>=80,['이름','생년월일']]

# 3. 수학이 80점 미만인 학생의 영어와 국어 점수
stu.loc[stu['수학']<80,['이름','영어','국어']]

# 4. 국어와 수학이 90점 이상인 학생의 이름, 수학, 국어 점수
stu.loc[(stu['국어']>=90)&(stu['수학']>=90),['이름','수학','국어']]

# 5. 모든 과목이 60점 미만인 학생의 번호, 이름, 생년월일
stu.loc[(stu['수학']<60)&(stu['국어']<60)&(stu['영어']<60),['번호','이름','생년월일']]

# 6. 대전 지역 학생들의 이름, 국어, 영어, 수학 점수
stu.loc[stu['지역명']=='대전']

# 문제1. 학생 데이터를 국어 성적으로 내림차순 정렬한 뒤 위에서 11개, 아래에서 7개 삭제
stu_sorted=stu.sort_values(by='국어', ascending=False)

stu_remove1=stu_sorted.iloc[11:]

stu_remove2=stu_remove1[:-7]

stu_remove2

    번호   이름  국어  영어  수학 지역명       생년월일
87  88  정혜희  95  69  76  서울 2050-09-20
46  47  정혜은  94  62  93  광주 2050-06-18
83  84  장혜은  94  76  99  서울 2050-07-12
12  13  장민진  94  70  74  대구 2050-08-12
10  11  이민은  94  91  98  광주 2050-09-07
..  ..  ...  ..  ..  ..  ..        ...
30  31  박현진  63  90  62  부산 2050-06-11
68  69  장지진  63  98  70  서울 2050-09-21
61  62  이준수  63  73  77  울산 2050-06-06
36  37  윤명진  62  93  95  광주 2050-04-27
20  21  이명수  62  88  62  서울 2050-04-01

[82 rows x 7 columns]

In [59]:
#  iloc로 데이터 접근
# 인덱스명을 숫자가 아닌 a,b,c라든가 야식1,야식2 등으로 변경한 경우. loc[0]을 하면 0이라는 인덱스가 없기 때문에 가져오지 않는다.
# 이때 iloc를 이용하면(iloc[0]) 수정 전의 0번 인덱스로 인식. 가져옴.

In [60]:
!pip install gitpython

Requirement already satisfied: gitpython in /usr/local/lib/python3.10/dist-packages (3.1.32)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.0)

In [61]:
USER_NAME ="joje3029"
USER_EMAIL = "joje3029@gmail.com"

!git config --global user.email $USER_EMAIL
!git config --global user.name $USER_NAME

In [63]:
notebook_file_path = "/content/Github"  # 노트북 파일 경로 지정
notebook_file_name = ""  # 노트북 파일 이름 지정

!jupyter nbconvert --to notebook --inplace --execute $notebook_file_path

import git

repo = git.Repo.init()
repo.index.add([notebook_file_name])
repo.index.commit("Initial commit")

origin_url = "https://github.com/joje3029/AI_Study.git"  # GitHub 저장소 URL
origin = repo.create_remote('origin', origin_url)

origin.push()

[NbConvertApp] Converting notebook /content/Github to notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py", line 423, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py", line 560, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py", line 488, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py", line 188, in from_filename
    with open(filename, encoding="utf-8") as f:
IsADirectoryError: [Errno 21] Is a directory: '/content/Github'

FileNotFoundError: ignored